title: [NLP Final Project]
description: [News-Driven FPL Insights Predicting Player Participation]

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
